// This file is a temporary placeholder for types that will be generated by OpenAPI later.

export interface LoginRequest {
    email: string;
    password: string;
  }
  
  export interface RegisterRequest {
    email: string;
    password: string;
  }
  
  export interface User {
    id: number;
    email: string;
    role: 'Admin' | 'User';
  }